name: Lint

on: [push, pull_request]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Use the latest major version
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Run Super-Linter for Dockerfiles only
        uses: super-linter/super-linter/slim@v7.3.0 # Use the latest major version
        env:
          # Set to 'false' to disable all linters by default
          VALIDATE_ALL_CODEBASE: false
          # Enable the Dockerfile linter (uses hadolint)
          VALIDATE_DOCKERFILE: true

          # Required for Super-Linter to report status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
